# Generated by Django 5.0.3 on 2024-03-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='other_links',
            field=models.TextField(blank=True, null=True),
        ),
    ]
